definitions:
  domain.AuthResponse:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: integer
      refreshToken:
        type: string
      tokenType:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  domain.Clinic:
    properties:
      abnNumber:
        type: string
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      logoURL:
        type: string
      name:
        type: string
      phone:
        type: string
      postcode:
        type: string
      state:
        type: string
      updatedAt:
        type: string
      website:
        type: string
    type: object
  domain.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  domain.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - email
    - password
    type: object
  domain.Session:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      expiresAt:
        type: string
      id:
        type: string
      ipAddress:
        type: string
      isActive:
        type: boolean
      updatedAt:
        type: string
      userAgent:
        type: string
      userId:
        type: string
    type: object
  domain.UpdateUserRequest:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
    type: object
  domain.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      is_email_verified:
        type: boolean
      last_name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password
      parameters:
      - description: Login request
        in: body
        name: login_request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Login a user
      tags:
      - Auth
  /auth/logout/{sessionId}:
    post:
      consumes:
      - application/json
      description: Logout a user with a session ID
      parameters:
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Logout a user
      tags:
      - Auth
  /auth/oauth:
    get:
      consumes:
      - application/json
      description: Initiate OAuth flow with a provider
      parameters:
      - description: Provider
        in: query
        name: provider
        required: true
        type: string
      - description: State
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Redirect to OAuth provider
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Initiate OAuth flow
      tags:
      - Auth
  /auth/oauth/{provider}/callback:
    get:
      consumes:
      - application/json
      description: OAuth callback with a provider
      parameters:
      - description: Provider
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: OAuth callback
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh a token with a refresh token
      parameters:
      - description: Refresh token
        in: body
        name: refreshToken
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Refresh a token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email and password
      parameters:
      - description: Register request
        in: body
        name: register_request
        required: true
        schema:
          $ref: '#/definitions/domain.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Register a new user
      tags:
      - Auth
  /clinic:
    get:
      consumes:
      - application/json
      description: Retrieve all clinics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Retrieve all clinics
      tags:
      - Clinic
    post:
      consumes:
      - application/json
      description: Create a new clinic with the given information
      parameters:
      - description: Clinic information
        in: body
        name: clinic
        required: true
        schema:
          $ref: '#/definitions/domain.Clinic'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create a new clinic
      tags:
      - Clinic
  /clinic/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a clinic by ID
      parameters:
      - description: Clinic ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Delete a clinic by ID
      tags:
      - Clinic
    get:
      consumes:
      - application/json
      description: Retrieve a clinic by ID
      parameters:
      - description: Clinic ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Retrieve a clinic by ID
      tags:
      - Clinic
    put:
      consumes:
      - application/json
      description: Update a clinic by ID with the given information
      parameters:
      - description: Clinic ID
        in: path
        name: id
        required: true
        type: string
      - description: Clinic information
        in: body
        name: clinic
        required: true
        schema:
          $ref: '#/definitions/domain.Clinic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update a clinic by ID
      tags:
      - Clinic
  /clinic/abn/{abnNumber}:
    get:
      consumes:
      - application/json
      description: Retrieve a clinic by ABN number
      parameters:
      - description: ABN number
        in: path
        name: abnNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Retrieve a clinic by ABN number
      tags:
      - Clinic
  /users/{userId}:
    get:
      consumes:
      - application/json
      description: Get current user by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get current user
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update current user by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Update user request
        in: body
        name: updateUserRequest
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update current user
      tags:
      - User
  /users/{userId}/sessions:
    get:
      consumes:
      - application/json
      description: Get active sessions by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Session'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get active sessions
      tags:
      - User
  /users/{userId}/sessions/{sessionId}:
    delete:
      consumes:
      - application/json
      description: Revoke a session by session ID and user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Session ID
        in: path
        name: sessionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Revoke a session
      tags:
      - User
swagger: "2.0"
